### ISSUE TITLE
Was this repository cleared out intentionally?

### ISSUE THREAD

**Issue by mildbyte** [dbt-labs/jaffle-shop-classic#1]
Hi,

We have an example that relies on the `demo/master` branch of this project (https://github.com/splitgraph/splitgraph/blob/master/examples/dbt/example.yaml#L47), which now seems to have gone away. Wondering if this was meant to be deleted? Thanks!

**Comment by clrcrl** [comment]
Yep, we do have a backup of it if we need to bring it back!

We cleared it out because the repo was doing too many things at once (e.g. it was trying to be a self contained repo, _and_ a best practices demo at the same time!). It felt like a fresh start to delete (read: rename and set to private) and recreate

I'm curious: was this a fork that broke? How was this repo being consumed?

**Comment by mildbyte** [comment]
Thanks for replying! 

We have a script that uses the main branch of this repo as a way to load some data into a PostgreSQL database, then switches to `demo/master` to run the actual dbt model that loads data from PG (the output ends up in an Asciinema -- the ultimate purpose is recording a demo of running dbt on top of our tool that does database versioning).

We could (and probably should!) fork it and keep the older version in our own organisation, if you could put that branch or the whole backup of the repo up somewhere temporarily?

**Comment by clrcrl** [comment]
I've set the repo to public temporarily: https://github.com/fishtown-analytics/jaffle_shop_archive

You might want to [duplicate the repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) rather than forking it, I suspect the fork is going to have a hard time if we change this back to private in the future!

**Comment by megazone23** [comment]
I was also using this repo.  My test jobs were setup against this repo as well by dbt representatives for a integration project.  I have JUnit tests which use this repo.  However, the way the project is configured now it fails to run successfully in DBT.  I noticed the yml file is slightly different.  There is a config-version: 2 where my dbt online account does not have that line.  Is this project configured for a newer version of dbt?

**Comment by mildbyte** [comment]
Perfect, I've duplicated it. Thanks for your help!
